### ISSUE TITLE
More Info Links in Readme are Broken

### ISSUE THREAD

**Issue by ptsouchlos** [scapix-com/cmodule#1]
Not sure if it's just me but both links under "more info" are broken (404 errors).

**Comment by NeroBurner** [comment]
Documentation works for me
https://www.scapix.com/cmodule

examples are not working for me
https://github.com/scapix-com/cmodule_test

**Comment by ptsouchlos** [comment]
Correct, docs seem to work now but examples do not.

**Comment by Boris-Rasin** [comment]
Thank you.
I have fixed both links.

**Comment by ptsouchlos** [comment]
Yup looks like they're working 👍
